export let weapons = [
  "Sploosh-o-matic",
  "Neo Sploosh-o-matic",
  "Splattershot Jr",
  "Custom Splattershot Jr",
  "Splash-o-matic",
  "Neo Splash-o-matic",
  "Aerospray MG",
  "Aerospray RG",
  "Splattershot",
  "Tentatek Splattershot",
  ".52 Gal",
  "NZAP '85",
  "NZAP '89",
  "Splattershot Pro",
  "Forge Splattershot Pro",
  ".96 Gal",
  ".96 Gal Deco",
  "Jet Squelcher",
  "Custom Jet Squelcher",
  "Splattershot Nova",
  "Annaki Splattershot Nova",
  "L-3 Nozzlenose",
  "L-3 Nozzlenose D",
  "H-3 Nozzlenose",
  "H-3 Nozzlenose D",
  "Cherry H-3 Nozzlenose",
  "Squeezer",
  "Carbon Roller",
  "Carbon Roller Deco",
  "Splat Roller",
  "Krak-On Splat Roller",
  "Dynamo Roller",
  "Gold Dynamo Roller",
  "Flingza Roller",
  "Big Swig Roller",
  "Big Swig Roller Express",
  "Classic Squiffer",
  "Splat Charger",
  "Z+F Splat Charger",
  "Splatterscope",
  "Z+F Splatterscope",
  "E-liter 4k",
  "E-liter 4k Scope",
  "Bamboozler 14 MK I",
  "Goo Tuber",
  "Custom Goo Tuber",
  "Snipewriter 5H",
  "Slosher",
  "Slosher Deco",
  "Tri Slosher",
  "Tri Slosher Nouveau",
  "Sloshing Machine",
  "Sloshing Machine Neo",
  "Bloblobber",
  "Bloblobber Deco",
  "Explosher",
  "Dread Wringer",
  "Mini Splatling",
  "Zink Mini Splatling",
  "Heavy Splatling",
  "Heavy Splatling Deco",
  "Hydra Splatling",
  "Ballpoint Splatling",
  "Ballpoint Splatling Nouveau",
  "Nautilus 47",
  "Heavy Edit Splatling",
  "Dapple Dualies",
  "Dapple Dualies Nouveau",
  "Splat Dualies",
  "Glooga Dualies",
  "Dapple Dualies",
  "Dualie Squelchers",
  "Custom Dualie Squelchers",
  "Dark Tetra Dualies",
  "Light Tetra Dualies",
  "Splat Brella",
  "Sorella Brella",
  "Tenta Brella",
  "Tenta Sorella Brella",
  "Undercover Brella",
  "Luna Blaster",
  "Luna Blaster Neo",
  "Blaster",
  "Range Blaster",
  "Clash Blaster",
  "Clash Blaster Neo",
  "Rapid Blaster",
  "Rapid Blaster Deco",
  "Kensa Rapid Blaster",
  "Rapid Blaster Pro",
  "Rapid Blaster Pro Deco",
  "S-Blast '92",
  "Inkbrush",
  "Inkbrush Nouveau",
  "Octobrush",
  "Octobrush Nouveau",
  "Tri-Stringer",
  "Inkline Tri-Stringer",
  "REEF-LUX 450",
  "Splatana Stamper",
  "Splatana Wiper",
  "Splatana Wiper Deco"
];
